### ISSUE TITLE
Update libuv version to 1.9.1

### ISSUE THREAD

**Issue by halter73** [aspnet/libuv-package#12]
https://github.com/libuv/libuv/releases/tag/v1.9.1

@moozzyk @muratg Most the stuff in the release notes seem relatively minor, and there's always some risk when updating dependencies like this, but this has been the latest stable release of libuv for a while now. We will also probably want to update libuv.dll/so/dylib in the 1.1 shared runtime.

**Comment by muratg** [comment]
I'm not seeing a lot of interesting fixes in the notes, and I'm leaning on waiting until next FTS release for this change.

@davidfowl @moozzyk @BrennanConroy @DamianEdwards thoughts?

**Comment by DamianEdwards** [comment]
Yeah seems a little late to take a dependency update like this. Seems better to slate it for 1.2

**Comment by muratg** [comment]
When doing this, we should also do https://github.com/aspnet/libuv-package/issues/11

**Comment by halter73** [comment]
Libuv [1.10.0](https://github.com/libuv/libuv/releases/tag/v1.10.0) was released 8 days ago.

**Comment by moozzyk** [comment]
Fixed in https://github.com/aspnet/libuv-build/commit/0297fa9769793851345a16970b26750726595408
