### ISSUE TITLE
Update the libuv used by Kestrel to one that has ControlGuard enabled

### ISSUE THREAD

**Issue by Eilon** [aspnet/libuv-package#25]
## Description

The Kestrel package currently uses a version of the libuv package that was built without [ControlGuard](https://docs.microsoft.com/en-us/windows/desktop/SecBP/control-flow-guard) enabled. A newer version of the libuv package exists, but is not yet referenced by Kestrel.

## Customer Impact

Customers wishing to use only libraries that have all the best practice compiler features enabled cannot use this library. We were contacted by Microsoft partner teams that they wish to use this.

## Regression from?

Not a regression.

## Risk

Very Low. Just need to use a newer version of the library that has this compiler feature enabled.

**Comment by Eilon** [comment]
Tagging @blowdart and @BethMantey.

**Comment by blowdart** [comment]
Needs performance testing to please Fowler, as this may end up slower.

**Comment by Eilon** [comment]
Handled this in an email with an alternative approach, so closing this issue.
