### ISSUE TITLE
libuv sources corresponding to NuGet package

### ISSUE THREAD

**Issue by f-camera** [aspnet/libuv-package#26]
Hello,
could you please help me understand (if possible) the exact version of libuv (referring to the source repo) that is in NuGet released packages?
It is a general question, but I'm particularly interested in [https://www.nuget.org/packages/Libuv/1.9.2](https://www.nuget.org/packages/Libuv/1.9.2).
I tried also looking at dll properties (File Version), but appear blank.

Would it be possible to have this info always retrievable from the package itself?
Thank you.

**Comment by Eilon** [comment]
Hi, I believe that the libuv NuGet package 1.9.2 corresponds to this libuv source commit: https://github.com/libuv/libuv/tree/229b3a4cc150aebd6561e6bd43076eafa7a03756
